#!/usr/bin/env python3
"""Qualify the programming-language corpus without running repository code."""

from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
import json
import os
from pathlib import Path
import re
import subprocess

from public_validation import APP, command, save_json, tracked_files


EXCLUDED_PARTS = {
    "vendor", "vendored", "node_modules", "target", "third_party", "third-party",
    "thirdparty", "external", "deps", "dist", "build", "generated",
}
MANIFEST = APP / "validation/development-languages.json"


def measure(root, language):
    extensions = {"." + extension for extension in language["extensions"]}
    paths, excluded = [], {}
    for path in tracked_files(root):
        if Path(path).suffix not in extensions:
            continue
        file = root / path
        if file.is_symlink() or not file.is_file():
            excluded[path] = "symlink or unavailable file"
            continue
        if set(Path(path).parts[:-1]) & EXCLUDED_PARTS:
            excluded[path] = "dependency/build/generated directory"
            continue
        with file.open("rb") as stream:
            header = stream.read(4096).decode("utf-8", errors="replace").lower()
        if header.startswith("version https://git-lfs.github.com/spec/"):
            excluded[path] = "unmaterialized LFS pointer"
            continue
        if re.search(r"(?:^|[._-])(?:generated|gen|g)\.[^.]+$", path) or (
            any(marker in header for marker in ("code generated", "automatically generated", "@generated", "<auto-generated"))
            and any(marker in header for marker in ("do not edit", "@generated", "<auto-generated"))
        ):
            excluded[path] = "generated filename/header"
            continue
        paths.append(path)
    reports = []
    for start in range(0, len(paths), 200):
        data = json.loads(command([
            "tokei", "--files", "--output", "json", "--no-ignore", "--hidden",
            "--", *paths[start:start + 200],
        ], root))
        for name, value in data.items():
            if name != "Total":
                reports.extend({**report, "tokei_language": name} for report in value.get("reports", []))
    measured = {report["name"].removeprefix("./") for report in reports}
    missing = sorted(set(paths) - measured)
    primary = sum(report["stats"]["code"] for report in reports)
    def code_including_embedded(stats):
        return stats["code"] + sum(code_including_embedded(child) for child in stats.get("blobs", {}).values())
    is_component = language["language"] in {"vue", "astro", "svelte"}
    total = sum(code_including_embedded(report["stats"]) for report in reports) if is_component else primary
    return {
        "language": language["language"], "extensions": language["extensions"],
        "code_lines": total, "files": len(paths), "unmeasured_files": missing,
        "primary_code_lines": primary, "embedded_code_lines": total - primary,
        "excluded": excluded, "reports": reports,
        "method": "Git-tracked supported extensions; comments/blanks, dependency/build directories, explicit generated markers and symlinks excluded; authored tests included. Component counts combine markup and embedded code/styles, and are not JS/TS-only counts.",
    }


def prepare_candidate(cache, slug, languages, revisions, minimum_lines, minimum_commits):
    key = slug.replace("/", "__")
    output = cache / "language-qualification" / key
    pin = output / "revision.json"
    url = f"https://github.com/{slug}.git"
    sha = revisions.get(slug)
    if pin.exists():
        saved = json.loads(pin.read_text())
        if saved["url"] != url or sha and saved["sha"] != sha:
            raise RuntimeError(f"Conflicting pinned revision for {slug}")
        sha = saved["sha"]
    if not sha:
        sha = command(["git", "ls-remote", url, "HEAD"]).split()[0]
    if not re.fullmatch(r"[0-9a-f]{40}", sha):
        raise RuntimeError(f"Invalid pinned revision for {slug}")
    save_json(pin, {"url": url, "sha": sha})
    root = cache / "language-repos" / key
    if not root.exists():
        root.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(["git", "clone", "--quiet", "--filter=blob:none", "--no-checkout", "--single-branch", "--no-tags", url, str(root)], check=True)
    if command(["git", "remote", "get-url", "origin"], root) != url:
        raise RuntimeError(f"Unexpected origin: {root}")
    if command(["git", "rev-parse", "--is-shallow-repository"], root) != "false":
        raise RuntimeError(f"Full history required: {root}")
    # The dedicated clone is only checked out once; subsequent runs must preserve it.
    if not (output / "checkout.json").exists():
        subprocess.run(["git", "checkout", "--quiet", "--detach", sha], cwd=root, check=True, env={**os.environ, "GIT_LFS_SKIP_SMUDGE": "1"})
        save_json(output / "checkout.json", {"sha": sha})
    if command(["git", "rev-parse", "HEAD"], root) != sha or command(["git", "status", "--porcelain", "--untracked-files=no"], root):
        raise RuntimeError(f"Qualification source changed: {root}")
    commits = int(command(["git", "rev-list", "--count", "HEAD"], root))
    for language in languages:
        report = measure(root, language)
        report.update(repository=slug, url=url, sha=sha, commits=commits, tokei_version=command(["tokei", "--version"]))
        report["qualified"] = report["code_lines"] >= minimum_lines and commits >= minimum_commits and not report["unmeasured_files"]
        save_json(output / f"{language['language']}.json", report)
        print(f"{language['language']} {slug}: code={report['code_lines']}, commits={commits}, qualified={report['qualified']}, unmeasured={len(report['unmeasured_files'])}", flush=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cache", type=Path, required=True)
    parser.add_argument("--language", action="append")
    parser.add_argument("--candidate", action="append")
    parser.add_argument("--jobs", type=int, choices=range(1, 5), default=2)
    args = parser.parse_args()
    data = json.loads(MANIFEST.read_text())
    known = {item["language"] for item in data["languages"]}
    if args.language and set(args.language) - known:
        parser.error(f"Unknown languages: {sorted(set(args.language) - known)}")
    groups = {}
    for language in data["languages"]:
        if args.language and language["language"] not in args.language:
            continue
        for slug in language["candidates"] if args.candidate else language.get("selected_candidates", language["candidates"]):
            if not args.candidate or slug in args.candidate:
                groups.setdefault(slug, []).append(language)
    if not groups:
        parser.error("No candidate matches the selected languages/repositories")
    errors = []
    cache = args.cache.expanduser().resolve()
    with ThreadPoolExecutor(max_workers=args.jobs) as pool:
        futures = {pool.submit(prepare_candidate, cache, slug, languages, data.get("revisions", {}), data["minimum_code_lines"], data["minimum_commits"]): slug for slug, languages in groups.items()}
        for future in as_completed(futures):
            try:
                future.result()
            except Exception as error:
                detail = {"repository": futures[future], "error": f"{type(error).__name__}: {error}"}
                errors.append(detail)
                print(json.dumps(detail), flush=True)
    save_json(cache / "language-qualification/last-errors.json", errors)
    return int(bool(errors))


if __name__ == "__main__":
    raise SystemExit(main())
