//! Connection-local task questions. The caller derives these from the user's task once;
//! retrieval queries never supply or replace them.

use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

pub const MAX_QUESTIONS: usize = 8;
/// Registration memory bound, independent of the evaluation context budget.
pub const MAX_REGISTRATION_BYTES: usize = 65_536;

#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum MatchMode {
    #[default]
    All,
    Any,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct TaskQuestion {
    /// Legacy labels are accepted and replaced with a server-generated routing ID.
    #[serde(default)]
    pub id: String,
    pub question: String,
    pub when_true: String,
    pub when_false: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct RegisteredTask {
    pub task_query: String,
    pub questions: Vec<TaskQuestion>,
    #[serde(default, rename = "match")]
    pub match_mode: MatchMode,
}

impl RegisteredTask {
    pub fn masked(&self) -> Self {
        let mut task = self.clone();
        task.task_query = crate::redact::source(&task.task_query).into_owned();
        for question in &mut task.questions {
            question.id = crate::redact::source(&question.id).into_owned();
            question.question = crate::redact::source(&question.question).into_owned();
            question.when_true = crate::redact::source(&question.when_true).into_owned();
            question.when_false = crate::redact::source(&question.when_false).into_owned();
        }
        task
    }

    fn validate(&self) -> Result<(), (i64, String)> {
        if self.task_query.trim().is_empty() {
            return Err(invalid("task_query must be nonempty"));
        }
        if self.questions.is_empty() || self.questions.len() > MAX_QUESTIONS {
            return Err(invalid(
                "questions must contain 1 to 8 focused yes/no questions",
            ));
        }
        for question in &self.questions {
            if [
                &question.question,
                &question.when_true,
                &question.when_false,
            ]
            .iter()
            .any(|text| text.trim().is_empty())
            {
                return Err(invalid(
                    "question, when_true and when_false must be nonempty strings",
                ));
            }
        }
        Ok(())
    }
}

fn invalid(reason: &str) -> (i64, String) {
    (-32602, format!("Invalid Jev task registration: {reason}. Call initial_instructions with task_query and questions (question, when_true, when_false); match is all or any. Question IDs are generated by the server."))
}

pub(crate) fn parse(
    arguments: &Value,
    is_required: bool,
) -> Result<Option<RegisteredTask>, (i64, String)> {
    if serde_json::to_vec(arguments).map_or(usize::MAX, |bytes| bytes.len())
        > MAX_REGISTRATION_BYTES
    {
        return Err(invalid("encoded registration exceeds 65536 bytes"));
    }
    if !is_required && arguments.get("questions").is_none() {
        // Disabled Jev keeps ordinary initialization and legacy text-only initialization
        // usable, but cannot leave an incomplete task for a later enabled filter.
        if let Some(goal) = arguments.get("task_query").filter(|value| !value.is_null()) {
            if !goal.is_string() {
                return Err(invalid("task_query must be a string"));
            }
        }
        return Ok(None);
    }
    let mut task: RegisteredTask = serde_json::from_value(arguments.clone())
        .map_err(|_| invalid("a goal and a nonempty structured questions list are required; legacy text-only registration is unsupported when Jev filtering is enabled"))?;
    task.validate()?;
    for (index, question) in task.questions.iter_mut().enumerate() {
        question.id = format!("q{index}");
    }
    Ok(Some(task))
}

pub(crate) fn schema(is_required: bool) -> Value {
    json!({
        "type":"object", "additionalProperties":false,
        "properties": {
            "task_query":{"type":"string","minLength":1,"description":"Nonempty complete user request, preserving targets, direction and scope. Entire registration: at most 65536 encoded UTF-8 bytes."},
            "questions":{"type":"array","minItems":1,"maxItems":MAX_QUESTIONS,"description":"1-8 focused yes/no criteria, each with nonempty question, when_true and when_false; yes means related. Judge supplied evidence: missing cross-file context means uncertainty, not false. Omit IDs.","items":{
                "type":"object","additionalProperties":false,"required":["question","when_true","when_false"],"properties":{
                    "id":{"type":"string","description":"Optional legacy label, ignored. Omit this field."},
                    "question":{"type":"string","minLength":1,"description":"One explicit yes/no question about this candidate and its supplied supporting evidence."},
                    "when_true":{"type":"string","minLength":1,"description":"Facts that establish yes."},
                    "when_false":{"type":"string","minLength":1,"description":"Facts that establish no, such as unrelated behavior; an absent name or missing context alone is insufficient."}
                }
            }},
            "match":{"type":"string","enum":["all","any"],"default":"all","description":"all (default) requires every criterion; any accepts at least one. Use any unless every criterion is mandatory."}
        },
        "required": if is_required { vec!["task_query","questions"] } else { vec![] }
    })
}
