(class_declaration name: (type_identifier) @definition.type)
(class_declaration name: (user_type) @definition.type)
(protocol_declaration name: (type_identifier) @definition.interface)
(typealias_declaration name: (type_identifier) @definition.type)
(function_declaration name: (simple_identifier) @definition.function)
(protocol_function_declaration name: (simple_identifier) @definition.method)
(property_declaration name: (pattern (simple_identifier) @definition.property))
(enum_entry name: (simple_identifier) @definition.constant)
(call_expression (simple_identifier) @reference.call)
