(package_declaration [(identifier) (scoped_identifier)] @definition.module)
(class_declaration name: (identifier) @definition.class)
(interface_declaration name: (identifier) @definition.interface)
(record_declaration name: (identifier) @definition.class)
(enum_declaration name: (identifier) @definition.enum)
(enum_constant name: (identifier) @definition.constant)
(method_declaration name: (identifier) @definition.method)
(constructor_declaration name: (identifier) @definition.method)
(field_declaration declarator: (variable_declarator name: (identifier) @definition.field))
(method_invocation name: (identifier) @reference.call)
