(package_clause name: (package_identifier) @definition.module)
(class_definition name: (identifier) @definition.class)
(trait_definition name: (identifier) @definition.interface)
(object_definition name: (identifier) @definition.object)
(enum_definition name: (identifier) @definition.enum)
(simple_enum_case name: (identifier) @definition.constant)
(full_enum_case name: (identifier) @definition.constant)
(function_definition name: [(identifier) (operator_identifier)] @definition.function)
(function_declaration name: [(identifier) (operator_identifier)] @definition.function)
(given_definition name: (identifier) @definition.variable)
(type_definition name: (type_identifier) @definition.type)
(val_definition pattern: (identifier) @definition.variable)
(var_definition pattern: (identifier) @definition.variable)
(call_expression (identifier) @reference.call)
